Fix missing dependency for mypy
Error was:
env-runner/environment.py:3: error: Library stubs not installed for "yaml" (or incompatible with Python 3.6)
env-runner/environment.py:3: note: Hint: "python3 -m pip install types-PyYAML"